### ISSUE TITLE
Tabs vs spaces

### ISSUE THREAD

**Issue by craigktreasure** [dotnetconfig/dotnet-config#122]
Not a deal breaker and more of a nitpick, but the `dotnet-config` tool appears to use tabs for indentation as opposed to spaces. This was a bit unexpected for me. Git uses and prefers spaces in a `.gitconfig` file. Curious if there is a reason for using tabs over spaces other than preference.

**Comment by kzu** [comment]
Yeah, no particular reason, just preference.

**Comment by kzu** [comment]
Given that git uses spaces in .gitconfig, perhaps we should switch to that too, in the spirit of standardization at least...

**Comment by kzu** [comment]
I actually just run the following command:

```bash
git config -f .netconfig.git foo.bar baz
```

and the file ended up with a tab before the variable:

```
[foo]
	bar = baz
````

So I'd say we're 100% compatible :)
