### ISSUE TITLE
Can't save empty/blank values

### ISSUE THREAD

**Issue by jackmang** [dotnetconfig/dotnet-config#145]
I am unable to save an empty string.  Example:
```
var conf = Config.Build(fileName);
conf.SetString("Section", "Variable", string.Empty);
```
I get System.ArgumentException Message=C:\ProgramData\XX\XXX\Login.config(0,13): Expected variable value after '='.
Is this expected?  My workaround was to set the value to a string containing two " values.
```
var valueToSet = "\"\""; 
var conf = Config.Build(fileName);
conf.SetString("Section", "Variable", valueToSet);
```
This works, but I'm wondering if I'm just doing something wrong.  It doesn't feel like an invalid scenario to want to save a blank setting value.

**Comment by kzu** [comment]
An empty string is invalid because an empty variable actually works like a boolean switch.

See the Values section: https://dotnetconfig.org/#format
